### ISSUE TITLE
#morning session

### ISSUE THREAD

**Issue by vic778** [cwaku/to-do-list#6]
- hey @cwaku your code is perfectly well represented but for its professionalism try to remove all the code in a comment please. it gives a professional scope

**Comment by cwaku** [comment]
> * hey @cwaku your code is perfectly well represented but for its professionalism try to remove all the code in a comment please. it gives a professional scope

Thank you for the review @vic778. I'll see to fix that

**Comment by basnetlaxmi** [comment]
Hi @cwaku ,  You have done a good job so far however, it would be better if you wrap up your Html content with the main semantic tag.

**Comment by cwaku** [comment]
> Hi @cwaku , You have done a good job so far however, it would be better if you wrap up your Html content with the main semantic tag.

Thank you for your comment. I really appreciate
